### ISSUE TITLE
thesis

### ISSUE THREAD

**Issue by Amri95** [ugm2/Thesis-SpikingNeuralNetworks#1]
hello, could you please send me your thesis link?

Best regards

**Comment by ugm2** [comment]
@Amri95 I've uploaded the thesis pdf to the repo:
https://github.com/ugm2/Thesis-SpikingNeuralNetworks/blob/master/Spiking%20Neural%20Networks%20A%20Review_Thesis.pdf

Sorry for the delay and thanks for the interest! Hope it helps
